# Generated by Django 4.1.3 on 2022-12-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_user_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField()),
                ('url', models.URLField(max_length=550)),
                ('desc', models.TextField()),
            ],
        ),
    ]
