# Generated by Django 4.1.3 on 2022-12-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(default='icon.png', upload_to='icons'),
            preserve_default=False,
        ),
    ]
