# Generated by Django 4.1.3 on 2022-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='sample.jpg', upload_to='projectimages'),
            preserve_default=False,
        ),
    ]
